version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    image: 4320_final_project_app
    container_name: flask_bus_app
    ports:
      - "5016:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"